[package]
name = "cloudshuttle-error-handling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Common error types and handling utilities for CloudShuttle services"
keywords = ["error", "handling", "cloudshuttle"]
categories = ["rust-patterns", "development-tools"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
http = "1.0"
sqlx = { workspace = true, optional = true }
async-trait.workspace = true
chrono.workspace = true

[features]
default = []
database = ["sqlx"]


